on:
  workflow_dispatch:
name: release-to-npm
permissions:
  contents: read
  id-token: write
jobs:
  release-to-npm:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org/"
          cache: "npm"
      - run: npm ci
      - run: npm run build

      - name: Publish
        run: |
          npm -v
          node -v
          npm stage publish --tag old-version
